### ISSUE TITLE
Is there anyway to use this in ESP-32 WROOM ?

### ISSUE THREAD

**Issue by canyazbahar** [bigbrodude6119/flipper-zero-evil-portal#11]
I'm really wondering is there any way to  run this on ESP-32 WROOM.

**Comment by bigbrodude6119** [comment]
Hey @canyazbahar, [yes it is definitely possible](https://imgur.com/a/1fTQ9Sl). Right now I am only making pre-compiled builds for the esp32s2 model but the ESP32 Wroom board seems to be a very popular alternative in the community. 

I am going to get some work done on the project tomorrow and I'll see if I can release a pre-compiled version.

If you would like to get it up and running on your board tonight you can follow the option 2 in the readme for flashing the board via the arduino ide.

**Comment by bigbrodude6119** [comment]
@canyazbahar I have attached a new file to the 0.0.2 release called `esp32_wroom.zip`. These are pre-compiled bins and you can follow the readme guide for the online flasher as if it were the official devboard.

Its not officially supported yet so things like the LED indication doesn't work but everything else should function as intended.

**Comment by canyazbahar** [comment]
don't know how much i appreciate it. thx for you hard work bigbrodude69
