### ISSUE TITLE
Honeypot other AP names?

### ISSUE THREAD

**Issue by leedave** [bigbrodude6119/flipper-zero-evil-portal#13]
Nice job you're doing here, I love the concept. 

One feature suggestion that could be interesting: 
Instead of manually entering a new AP name, would it also be an option to select an SSID name from a list of existing AP's and just have the device sitting there pretending to be this AP?

**Comment by bigbrodude6119** [comment]
That is a really good idea, I like it a lot! 

I'll update the list of to-do items today. Thank you for the feedback

**Comment by bigbrodude6119** [comment]
I added this to the "Todo" section of the main readme. Thanks again!
