### ISSUE TITLE
Can not load evil portal

### ISSUE THREAD

**Issue by D4N2135** [bigbrodude6119/flipper-zero-evil-portal#90]
Could anyone help me with this issue please, many thanks in advance!
![image](https://github.com/bigbrodude6119/flipper-zero-evil-portal/assets/154370914/f2b15813-d0db-47b9-b00a-ed2dc0602175)
![image](https://github.com/bigbrodude6119/flipper-zero-evil-portal/assets/154370914/529cc7f0-4431-4a13-9a72-a1181eee24ba)
![image](https://github.com/bigbrodude6119/flipper-zero-evil-portal/assets/154370914/21792c2c-7434-4706-8523-184d6c37ad65)

**Comment by ll022** [comment]
having same issue

**Comment by D4N2135** [comment]
**SOLVED** see the link attached https://www.reddit.com/r/flipperzero/s/Prex0PHUGB
